exclude: .html
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v6.0.0
    hooks:
      - id: check-yaml
        language: python
      - id: check-json
        language: python
      - id: end-of-file-fixer
        language: python
      - id: trailing-whitespace
        language: python
      - id: check-docstring-first
        language: python
      - id: requirements-txt-fixer
        language: python
      - id: check-merge-conflict
        language: python
      - id: check-toml
        language: python
      - id: check-xml
        language: python
      - id: check-ast
        language: python
      - id: check-builtin-literals
        language: python
  - repo: https://github.com/JanEricNitschke/pymend
    rev: "v1.1.0"
    hooks:
      - id: pymend
        language: python
        args: ["--write", "--check", "--output-style=google"]
  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args:
          - '--fix'
          - '--exit-non-zero-on-fix'
      - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    rev: v1.36.3
    hooks:
      - id: typos
        args: []
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint download_pdfs.py
        language: system
        types: [python]
        pass_filenames: false
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
